import { File, Paths } from "expo-file-system";
import type { SurveyTemplate, TemplateField, FormData } from "@/types/survey-template";
import type { ReleveSpeciesEntry } from "@/types/releve";
import { RELEVE_SECTIONS, COMMON_FLORA } from "@/constants/releve-data";
import { FOSSITT_LEVEL3 } from "@/components/habitat-picker";

/**
 * Test data generators for dev-only auto-fill. Keeps fake-but-plausible
 * values so the form flow (validation, save, sync, cache, reporting) can
 * be exercised end-to-end without manual typing.
 */

// Valid 1x1 white JPEG. Small but real bytes — enough to exercise the upload
// pipeline. Watermark canvas may produce degenerate output at this size; the
// photo-service catches that and falls back to the original upload.
const TEST_PHOTO_BASE64 =
  "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACv/EABQBAQAAAAAAAAAAAAAAAAAAAAb/2gAMAwEAAhADEAAAAU//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/AH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AH//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AH//2Q==";

/**
 * Writes the hardcoded test JPEG to the app's cache dir and returns the
 * file:// URI. Each call writes to a unique filename so repeated presses
 * don't collide.
 */
export async function createTestPhotoUri(): Promise<string> {
  const name = `dev-photo-${Date.now()}-${Math.random().toString(36).slice(2, 7)}.jpg`;
  const file = new File(Paths.cache, name);
  file.create({ overwrite: true });
  file.write(TEST_PHOTO_BASE64, { encoding: "base64" });
  return file.uri;
}

function valueForTextField(field: TemplateField): string {
  const key = field.key.toLowerCase();
  if (key.includes("name") || key.includes("observer") || key.includes("recorder") || key.includes("surveyor")) return "Test Observer";
  if (key.includes("weather") || key.includes("condition")) return "Overcast, light breeze";
  if (key.includes("note") || key.includes("comment") || key.includes("description") || key.includes("remark")) return "Dev test — autogenerated entry.";
  if (key.includes("location") || key.includes("site")) return "Test Site A";
  if (key.includes("time")) return "10:30";
  if (key.includes("date")) return new Date().toISOString().split("T")[0];
  if (key.includes("wind")) return "Light SW";
  return `Test ${field.label}`;
}

function valueForNumberField(field: TemplateField): number {
  const key = field.key.toLowerCase();
  const min = typeof field.min === "number" ? field.min : 0;
  const max = typeof field.max === "number" ? field.max : 100;

  if (key.includes("lat")) return 53.3498;
  if (key.includes("lng") || key.includes("lon")) return -6.2603;
  if (key.includes("accuracy")) return 5;
  if (key.includes("temperature") || key === "temp") return 15;
  if (key.includes("count") || key.includes("number") || key.includes("individuals")) return 3;
  if (key.includes("percent") || key.includes("pct") || key.includes("%")) return 50;
  if (key.includes("height")) return 10;
  if (key.includes("depth")) return 2;
  if (key.includes("duration") || key.includes("minutes")) return 15;

  const mid = Math.round((min + max) / 2);
  return Number.isFinite(mid) && mid !== 0 ? mid : 5;
}

function valueForField(field: TemplateField): string | number | null {
  if (field.type === "select") {
    return field.options?.[0]?.value ?? null;
  }
  if (field.type === "number") {
    return valueForNumberField(field);
  }
  // text + textarea
  return valueForTextField(field);
}

/**
 * Generate FormData for a generic survey from its template.
 * Shape: { [sectionId]: { [fieldKey]: value } }.
 */
export function generateTestFormData(template: SurveyTemplate): FormData {
  const result: FormData = {};
  const sections = template.default_fields?.sections ?? [];

  for (const section of sections) {
    if (!section.enabled) continue;
    const sectionValues: Record<string, string | number | null> = {};
    for (const field of section.fields) {
      const v = valueForField(field);
      if (v !== null && v !== undefined) sectionValues[field.key] = v;
    }
    if (Object.keys(sectionValues).length > 0) {
      result[section.id] = sectionValues;
    }
  }

  return result;
}

/**
 * Generate Relevé form data using the fixed RELEVE_SECTIONS schema.
 * Caller should merge the returned `formData` on top of existing basic
 * defaults (releve_code / recorder / site_name) rather than overwriting,
 * so generated `releve_code` sequence is preserved.
 */
export function generateTestReleveFormData(): {
  formData: FormData;
  species: ReleveSpeciesEntry[];
} {
  const firstFossittCode = FOSSITT_LEVEL3[0]?.code ?? "GA1";

  const values: Record<string, string | number> = {
    releve_area_sqm: 4,
    survey_x_coord: 53.3498,
    survey_y_coord: -6.2603,
    accuracy_m: 5,
    habitat_type: firstFossittCode,
    soil_type: "Peat",
    soil_stability: "Firm",
    aspect: "S",
    slope_degrees: 5,
    max_height_trees_m: 8,
    max_height_shrubs_cm: 150,
    max_height_bryophytes_cm: 5,
    max_height_graminea_cm: 40,
    max_height_forbs_cm: 30,
    median_height_graminea_cm: 20,
    median_height_forbs_cm: 15,
    total_vegetation_cover_pct: 90,
    cover_graminea_pct: 40,
    cover_forbs_pct: 25,
    cover_mosses_liverworts_pct: 15,
    cover_trees_pct: 5,
    cover_shrubs_pct: 5,
    cover_litter_pct: 5,
    cover_bare_soil_pct: 3,
    cover_bare_rock_pct: 1,
    cover_open_water_pct: 1,
    other_species_proximity: "Dev test — sample proximity notes.",
    fauna_observations: "Dev test — sample fauna observations.",
    releve_comment: "Dev test — autogenerated relevé entry.",
  };

  const formData: FormData = {};
  for (const section of RELEVE_SECTIONS) {
    if (section.id === "basic") continue; // preserve defaults set on mount
    const sectionValues: Record<string, string | number | null> = {};
    for (const field of section.fields) {
      if (field.key in values) sectionValues[field.key] = values[field.key];
    }
    if (Object.keys(sectionValues).length > 0) formData[section.id] = sectionValues;
  }

  const pickFlora = COMMON_FLORA.slice(0, 3);
  const domins = [6, 5, 4];
  const pcts = [30, 15, 8];
  const species: ReleveSpeciesEntry[] = pickFlora.map((f, i) => ({
    species_name_latin: f.latin,
    species_name_english: f.english,
    species_cover_domin: domins[i] ?? null,
    species_cover_pct: pcts[i] ?? null,
    notes: null,
  }));

  return { formData, species };
}
