import { supabase } from "@/lib/supabase";
import {
  getCachedTemplate, getCachedProjects, cacheTemplate,
  cacheHabitat, cacheTargetNote,
  getAllPendingSurveys, getAllPendingPhotos,
  dropConflictedSurveys, dropConflictedPhotos,
  getDatabase,
} from "@/lib/database";
import { clearLocationCache } from "@/lib/location";
import { saveSurvey } from "@/lib/survey-save";
import { getReleveDefaults } from "@/lib/releve-save";
import { generateTestFormData, generateTestReleveFormData } from "@/lib/dev-fill-data";
import { FOSSITT_LEVEL3 } from "@/components/habitat-picker";
import type { SurveyTemplate, FormData } from "@/types/survey-template";

/**
 * Dev-only helpers that the DevTool component calls. Split out so the
 * component file stays within the 400-line limit.
 */

export async function loadTemplateForType(surveyType: string): Promise<SurveyTemplate | null> {
  try {
    const { data } = await supabase
      .from("survey_templates")
      .select("id, name, survey_type, is_active, default_fields")
      .eq("survey_type", surveyType)
      .single();
    if (data) {
      await cacheTemplate({ surveyType: data.survey_type, name: data.name, defaultFields: data.default_fields ?? {} });
      return data as SurveyTemplate;
    }
  } catch { /* offline — fall back to cache */ }

  const cached = await getCachedTemplate(surveyType);
  if (!cached) return null;
  const parsed = JSON.parse(cached.default_fields);
  return { id: cached.survey_type, name: cached.name, survey_type: cached.survey_type, is_active: true, default_fields: parsed };
}

export type CreateResult = "online" | "offline" | "failed";

export async function createOneSurvey(surveyType: string, projectId: string): Promise<CreateResult> {
  const cachedProjects = await getCachedProjects();
  const projectName = cachedProjects.find((p) => p.id === projectId)?.name ?? "";

  let formData: FormData;
  if (surveyType === "releve_survey") {
    const defaults = await getReleveDefaults({ projectId, projectName });
    const { formData: generated, species } = generateTestReleveFormData();
    formData = {
      ...generated,
      basic: {
        releve_code: defaults.releve_code,
        recorder: defaults.recorder || "Test Observer",
        site_name: defaults.site_name,
        releve_area_sqm: 4,
      },
    };
    (formData as Record<string, unknown>).species = species;
  } else {
    const template = await loadTemplateForType(surveyType);
    if (!template) return "failed";
    formData = generateTestFormData(template);
  }

  const result = await saveSurvey({
    surveyId: null, projectId, projectName, surveyType,
    formData, markComplete: false, pendingPhotoUris: [],
    siteId: null, surveyorId: null,
  });
  if (!result.success) return "failed";
  return result.offline ? "offline" : "online";
}

// Small rectangle around Dublin (~100m × 70m); keeps each test call unique
// by shifting the lat/lng by a random delta so polygons don't overlap.
function makeTestBoundary(): { wkt: string; lat: number; lng: number } {
  const jitterLat = (Math.random() - 0.5) * 0.01;
  const jitterLng = (Math.random() - 0.5) * 0.01;
  const lat = 53.3498 + jitterLat;
  const lng = -6.2603 + jitterLng;
  const d = 0.0007;
  const wkt =
    `SRID=4326;POLYGON((${lng - d} ${lat - d}, ${lng + d} ${lat - d}, ` +
    `${lng + d} ${lat + d}, ${lng - d} ${lat + d}, ${lng - d} ${lat - d}))`;
  return { wkt, lat, lng };
}

export type ProjectDataResult = { ok: true } | { ok: false; reason: string };

export async function createTestHabitat(projectId: string): Promise<ProjectDataResult> {
  const fossitt = FOSSITT_LEVEL3[0] ?? { code: "GA1", name: "Improved agricultural grassland" };
  const boundary = makeTestBoundary();

  const { data, error } = await supabase
    .from("habitat_polygons")
    .insert({
      project_id: projectId,
      fossitt_code: fossitt.code,
      fossitt_name: fossitt.name,
      boundary: boundary.wkt,
      area_hectares: 0.25,
      condition: "good",
      notes: "Dev test — autogenerated habitat.",
      listed_species: ["Agrostis capillaris", "Holcus lanatus"],
      threats: ["grazing"],
      evaluation: "local",
      include_in_report: true,
    })
    .select("id")
    .single();

  if (error || !data) return { ok: false, reason: error?.message ?? "unknown error" };

  await cacheHabitat({
    id: data.id, projectId, fossittCode: fossitt.code, fossittName: fossitt.name,
    areaHectares: 0.25, condition: "good", notes: "Dev test — autogenerated habitat.",
    euAnnexCode: null, surveyMethod: null, evaluation: "local",
    listedSpecies: ["Agrostis capillaris", "Holcus lanatus"],
    threats: ["grazing"], photos: [], siteId: null,
  });
  return { ok: true };
}

export async function createTestTargetNote(projectId: string): Promise<ProjectDataResult> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { ok: false, reason: "not authenticated" };

  const jitterLat = (Math.random() - 0.5) * 0.01;
  const jitterLng = (Math.random() - 0.5) * 0.01;
  const lat = 53.3498 + jitterLat;
  const lng = -6.2603 + jitterLng;
  const title = `Dev test target note ${Date.now() % 10000}`;

  const { data, error } = await supabase
    .from("target_notes")
    .insert({
      project_id: projectId,
      category: "fauna",
      title,
      description: "Dev test — autogenerated target note.",
      location: `SRID=4326;POINT(${lng} ${lat})`,
      priority: "normal",
      is_verified: false,
      created_by: user.id,
      include_in_report: true,
    })
    .select("id")
    .single();

  if (error || !data) return { ok: false, reason: error?.message ?? "unknown error" };

  await cacheTargetNote({
    id: data.id, projectId,
    category: "fauna",
    title,
    description: "Dev test — autogenerated target note.",
    priority: "normal", isVerified: false,
    locationText: `POINT(${lng} ${lat})`, photos: [], siteId: null,
  });
  return { ok: true };
}

/**
 * Build a single multi-line diagnostic string from the pending queue.
 * Includes sync_status, retry count, and the last error for each row so
 * the user can see WHY something is stuck (typical case: RLS violation
 * because the project belongs to a different organization).
 */
export async function inspectPending(): Promise<string> {
  const [surveys, photos] = await Promise.all([getAllPendingSurveys(), getAllPendingPhotos()]);

  const bucket = (rows: { sync_status: string }[]): Record<string, number> => {
    const out: Record<string, number> = {};
    for (const r of rows) out[r.sync_status] = (out[r.sync_status] ?? 0) + 1;
    return out;
  };

  const surveysByStatus = bucket(surveys);
  const photosByStatus = bucket(photos);

  const lines: string[] = [];
  lines.push(`Surveys: ${surveys.length} (pending: ${surveysByStatus.pending ?? 0}, conflict: ${surveysByStatus.conflict ?? 0})`);
  lines.push(`Photos: ${photos.length} (pending: ${photosByStatus.pending ?? 0}, conflict: ${photosByStatus.conflict ?? 0})`);

  if (surveys.length > 0) {
    lines.push("", "— SURVEYS —");
    for (const s of surveys.slice(0, 6)) {
      lines.push(`• ${s.sync_status.toUpperCase()} ${s.survey_type} (retry ${s.retry_count ?? 0})`);
      if (s.last_error) lines.push(`  ↳ ${s.last_error}`);
    }
    if (surveys.length > 6) lines.push(`  … and ${surveys.length - 6} more`);
  }
  if (photos.length > 0) {
    lines.push("", "— PHOTOS —");
    for (const p of photos.slice(0, 6)) {
      lines.push(`• ${p.sync_status.toUpperCase()} survey=${p.survey_id ? "remote" : "local"} (retry ${p.retry_count ?? 0})`);
      if (p.last_error) lines.push(`  ↳ ${p.last_error}`);
    }
    if (photos.length > 6) lines.push(`  … and ${photos.length - 6} more`);
  }

  if (surveys.length === 0 && photos.length === 0) lines.push("", "Queue is empty.");
  return lines.join("\n");
}

export async function dropAllConflicts(): Promise<{ surveys: number; photos: number }> {
  const [surveys, photos] = await Promise.all([
    dropConflictedSurveys(),
    dropConflictedPhotos(),
  ]);
  return { surveys, photos };
}

/**
 * Reset the first-launch location prompt so the modal fires again on the
 * next render. Also clears the in-memory location cache so a fresh GPS fix
 * is taken next time getLocation() is called. Useful for QA test runs.
 */
export async function resetLocationPrompt(): Promise<void> {
  const db = await getDatabase();
  await db.runAsync(`DELETE FROM app_state WHERE key = ?`, "location_prompt_shown");
  clearLocationCache();
}
